# Generated by Django 2.2.7 on 2020-03-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blobby',
            name='_data_qbc',
            field=models.BinaryField(blank=True, db_column='data2'),
        ),
    ]
