# Generated by Django 2.2.7 on 2020-03-31 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_auto_20200330_1118"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Original",
        ),
    ]
