# Generated by Django 2.2.7 on 2020-06-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_original'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='videogenerator',
            order_with_respect_to='video_name',
        ),
    ]
