# Generated by Django 2.2.7 on 2020-06-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200619_1138'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='videogenerator',
            order_with_respect_to=None,
        ),
    ]
